### ISSUE TITLE
Github Actions job that automates IaSQL code reviews

### ISSUE THREAD

**Issue by depombo** [iasql/iasql#2360]
suggested by @yrobla. the Github actions job should take a pg connection string and assumes it will run on the repo it is in. It should have a button via `workflow_dispatch` hook that accepts a branch name to generate a PR on. markdown goes in `transactions/` folder. Merging the PR triggers a CI job that calls `iasql_commit`

**Comment by mtp1376** [comment]
- https://iasql.com/docs/review/
- https://iasql.com/docs/envs/
- https://github.com/iasql/iasql/blob/main/rfcs/007%20-%20Peer%20review%20infra%20changes.md

**Comment by mtp1376** [comment]
```yml
name: 'IaSQL Code Review'

on:
  workflow_dispatch:
    inputs:
      dbConnectionString:
        description: 'IaSQL database connection string'
        required: true
      prTitle:
        description: 'Title for the PR'
        required: true
      prDescription:
        description: 'Description for the PR'
        required: false

jobs:
  create-pr:
    name: Create PR - ${{ inputs.prTitle }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create markdown file
        id: create-markdown
        run: |
          PR=$(psql "$CON_STR" -AXqtc "SELECT * FROM iasql_create_review('$PR_TITLE', '$PR_DESCRIPTION');")
          mkdir -p transactions
          cd transactions
          echo "$PR" > "$PR_TITLE.md"
          echo 'pr<<EOF' >> $GITHUB_OUTPUT
          echo "$PR" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          CON_STR: ${{ inputs.dbConnectionString }}
          PR_TITLE: ${{ inputs.prTitle }}
          PR_DESCRIPTION: ${{ inputs.prDescription }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ inputs.prTitle }}
          delete-branch: false
          title: ${{ inputs.prTitle }}
          body: ${{ steps.create-markdown.outputs.pr }}
          branch: ${{ github.ref_name }}
          base: 'main'
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
```

**Comment by mtp1376** [comment]
1. Make changes in the IaSQL database, for example:
```sql
SELECT iasql_begin();
INSERT INTO bucket (name) VALUES ('mtp-test-x-15');
```
2. Create a Github Actions secret named `IASQL_CONNECTION_STRING` and paste the connection string into it (don't include `?sslmode=noverify`.
3. Trigger "IaSQL Create PR" job
<img width="329" alt="image" src="https://user-images.githubusercontent.com/5357435/229577842-3168272a-2ff0-4d9c-8937-d372b9a10fbe.png">
It will create a PR as follows:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/5357435/229577926-2cd75f94-ab8f-4375-ac61-40b8d012e30f.png">
4. Merge the PR. It will run a job will execute `iasql_commit`:
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/5357435/229578676-76da17c6-dba8-42e5-ac9b-93d5edb9d4bd.png">

**Comment by mtp1376** [comment]
<details>
  <summary>create-pr.yml</summary>  

```yml
name: 'IaSQL Create PR'

on:
  workflow_dispatch:
    inputs:
      prTitle:
        description: 'Title for the PR'
        required: true
      prDescription:
        description: 'Description for the PR'
        required: false

jobs:
  create-pr:
    name: Create PR - ${{ inputs.prTitle }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create markdown file
        id: create-markdown
        run: |
          PR=$(psql "$CON_STR" -AXqtc "SELECT * FROM iasql_create_review('$PR_TITLE', '$PR_DESCRIPTION');")
          mkdir -p transactions
          cd transactions
          echo "$PR" > "$PR_TITLE.md"
          echo 'pr<<EOF' >> $GITHUB_OUTPUT
          echo "$PR" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          CON_STR: ${{ secrets.IASQL_CONNECTION_STRING }}
          PR_TITLE: ${{ inputs.prTitle }}
          PR_DESCRIPTION: ${{ inputs.prDescription }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: ${{ inputs.prTitle }}
          delete-branch: false
          title: ${{ inputs.prTitle }}
          body: ${{ steps.create-markdown.outputs.pr }}
          branch: iasql/code-review
          branch-suffix: timestamp
          base: 'main'
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

```
</details>

<details>
  <summary>pr-merged.yml</summary>  

```yml
name: 'IaSQL Commit Changes on PR Merge'

on:
  pull_request:
    types:
      - closed

jobs:
  commit_changes:
    name: Commit changes to IaSQL from merged PR
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'iasql/code-review-')

    runs-on: ubuntu-latest
    steps:
      - name: Run iasql_commit
        run: |
            echo "Running iasql_commit"
            COMMIT_RESULT=$(psql "$CON_STR" -AXqtc "SELECT * FROM iasql_commit($PR_URL);")
            echo "Commit result: $COMMIT_RESULT"
          env:
            CON_STR: ${{ secrets.IASQL_CONNECTION_STRING }}
            PR_URL: ${{ github.event.pull_request.url }}
```
</details>
